/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'suportesoftbox' at '06/12/16 11:27' with Gradle 2.14.1
 *
 * @author suportesoftbox, @date 06/12/16 11:27
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
